# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm_dialog(object):
    def setupUi(self, confirm_dialog):
        confirm_dialog.setObjectName("confirm_dialog")
        confirm_dialog.resize(300, 114)
        confirm_dialog.setMinimumSize(QtCore.QSize(300, 114))
        confirm_dialog.setMaximumSize(QtCore.QSize(300, 114))
        self.verticalLayout = QtWidgets.QVBoxLayout(confirm_dialog)
        self.verticalLayout.setContentsMargins(20, -1, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirm_msg = QtWidgets.QLabel(confirm_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_msg.setFont(font)
        self.confirm_msg.setObjectName("confirm_msg")
        self.verticalLayout.addWidget(self.confirm_msg)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.no_button = QtWidgets.QPushButton(confirm_dialog)
        self.no_button.setMinimumSize(QtCore.QSize(80, 30))
        self.no_button.setMaximumSize(QtCore.QSize(80, 25))
        self.no_button.setObjectName("no_button")
        self.horizontalLayout.addWidget(self.no_button)
        self.yes_button = QtWidgets.QPushButton(confirm_dialog)
        self.yes_button.setMinimumSize(QtCore.QSize(80, 30))
        self.yes_button.setMaximumSize(QtCore.QSize(80, 25))
        self.yes_button.setObjectName("yes_button")
        self.horizontalLayout.addWidget(self.yes_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(confirm_dialog)
        QtCore.QMetaObject.connectSlotsByName(confirm_dialog)

    def retranslateUi(self, confirm_dialog):
        _translate = QtCore.QCoreApplication.translate
        confirm_dialog.setWindowTitle(_translate("confirm_dialog", "Dialog"))
        self.confirm_msg.setText(_translate("confirm_dialog", "Did you sign in successfully ?"))
        self.no_button.setText(_translate("confirm_dialog", "No"))
        self.yes_button.setText(_translate("confirm_dialog", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirm_dialog = QtWidgets.QDialog()
    ui = Ui_confirm_dialog()
    ui.setupUi(confirm_dialog)
    confirm_dialog.show()
    sys.exit(app.exec_())
