# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_system_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_system_stat(object):
    def setupUi(self, system_stat):
        system_stat.setObjectName("system_stat")
        system_stat.resize(393, 180)
        system_stat.setMinimumSize(QtCore.QSize(300, 180))
        system_stat.setMaximumSize(QtCore.QSize(450, 180))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(system_stat)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(system_stat)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.database_msg = QtWidgets.QLabel(system_stat)
        self.database_msg.setMinimumSize(QtCore.QSize(0, 35))
        self.database_msg.setMaximumSize(QtCore.QSize(16777215, 35))
        self.database_msg.setObjectName("database_msg")
        self.horizontalLayout_2.addWidget(self.database_msg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(system_stat)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.ipv4_msg = QtWidgets.QLabel(system_stat)
        self.ipv4_msg.setMinimumSize(QtCore.QSize(0, 35))
        self.ipv4_msg.setMaximumSize(QtCore.QSize(16777215, 35))
        self.ipv4_msg.setObjectName("ipv4_msg")
        self.horizontalLayout_3.addWidget(self.ipv4_msg)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(system_stat)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.ip_conflict_msg = QtWidgets.QLabel(system_stat)
        self.ip_conflict_msg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ip_conflict_msg.setObjectName("ip_conflict_msg")
        self.horizontalLayout_4.addWidget(self.ip_conflict_msg)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(system_stat)
        QtCore.QMetaObject.connectSlotsByName(system_stat)

    def retranslateUi(self, system_stat):
        _translate = QtCore.QCoreApplication.translate
        system_stat.setWindowTitle(_translate("system_stat", "System Status"))
        self.label.setText(_translate("system_stat", "Database :"))
        self.database_msg.setText(_translate("system_stat", "Loading .."))
        self.label_2.setText(_translate("system_stat", "IPV4 :"))
        self.ipv4_msg.setText(_translate("system_stat", "Loading .."))
        self.label_3.setText(_translate("system_stat", "IP Conflict :"))
        self.ip_conflict_msg.setText(_translate("system_stat", "Loading .."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    system_stat = QtWidgets.QDialog()
    ui = Ui_system_stat()
    ui.setupUi(system_stat)
    system_stat.show()
    sys.exit(app.exec_())
